version: '3'

services:
    portfolio-box:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: portfolio-box
        ports:
            - '5000:5000'
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        volumes:
            - /var/docker/portfolio-box/data:/data
        networks:
            - mariadb_mariadb_network

networks:
  mariadb_mariadb_network:
    external: true
    driver: bridge